version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-oauthtest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: oauthtest
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
